import uuid
from services.db import get_client, insert_row


SEED_PRODUCTS = [
    {
        "id": "AASH-ATTA-5KG",
        "name": "Aashirvaad Atta 5kg",
        "brand": "Aashirvaad",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 200,
        "sellPrice": 220,
        "mrp": 225,
        "quantity": 0,
        "reorderLevel": 5,
        "hsnCode": "1101",
        "gstRate": 0,
    },
    {
        "id": "AASH-ATTA-10KG",
        "name": "Aashirvaad Atta 10kg",
        "brand": "Aashirvaad",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 390,
        "sellPrice": 430,
        "mrp": 440,
        "quantity": 0,
        "reorderLevel": 5,
        "hsnCode": "1101",
        "gstRate": 0,
    },
    {
        "id": "TATA-SALT-1KG",
        "name": "Tata Salt 1kg",
        "brand": "Tata",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 20,
        "sellPrice": 24,
        "mrp": 25,
        "quantity": 0,
        "reorderLevel": 10,
        "hsnCode": "2501",
        "gstRate": 0,
    },
    {
        "id": "AMUL-BTR-100G",
        "name": "Amul Butter 100g",
        "brand": "Amul",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 48,
        "sellPrice": 52,
        "mrp": 54,
        "quantity": 0,
        "reorderLevel": 10,
        "hsnCode": "0405",
        "gstRate": 12,
    },
    {
        "id": "AMUL-BTR-500G",
        "name": "Amul Butter 500g",
        "brand": "Amul",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 240,
        "sellPrice": 260,
        "mrp": 270,
        "quantity": 0,
        "reorderLevel": 5,
        "hsnCode": "0405",
        "gstRate": 12,
    },
    {
        "id": "FRT-SUN-OIL-1L",
        "name": "Fortune Sunflower Oil 1L",
        "brand": "Fortune",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 120,
        "sellPrice": 135,
        "mrp": 140,
        "quantity": 0,
        "reorderLevel": 10,
        "hsnCode": "1512",
        "gstRate": 5,
    },
    {
        "id": "MAGGI-70G",
        "name": "Maggi 70g",
        "brand": "Nestle",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 12,
        "sellPrice": 14,
        "mrp": 14,
        "quantity": 0,
        "reorderLevel": 20,
        "hsnCode": "1902",
        "gstRate": 18,
    },
    {
        "id": "MAGGI-140G",
        "name": "Maggi 140g",
        "brand": "Nestle",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 24,
        "sellPrice": 27,
        "mrp": 28,
        "quantity": 0,
        "reorderLevel": 10,
        "hsnCode": "1902",
        "gstRate": 18,
    },
    {
        "id": "PARLE-G-800G",
        "name": "Parle-G 800g",
        "brand": "Parle",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 65,
        "sellPrice": 72,
        "mrp": 75,
        "quantity": 0,
        "reorderLevel": 10,
        "hsnCode": "1905",
        "gstRate": 18,
    },
    {
        "id": "SURF-EXCEL-1KG",
        "name": "Surf Excel 1kg",
        "brand": "HUL",
        "isLoose": False,
        "unit": "packet",
        "costPrice": 115,
        "sellPrice": 125,
        "mrp": 130,
        "quantity": 0,
        "reorderLevel": 5,
        "hsnCode": "3402",
        "gstRate": 18,
    },
    {
        "id": "LOOSE-SUGAR",
        "name": "Loose Sugar",
        "brand": None,
        "isLoose": True,
        "unit": "kg",
        "costPrice": 38,
        "sellPrice": 42,
        "mrp": 42,
        "quantity": 0,
        "reorderLevel": 20,
        "hsnCode": "1701",
        "gstRate": 5,
    },
    {
        "id": "LOOSE-RICE",
        "name": "Loose Rice (Basmati)",
        "brand": None,
        "isLoose": True,
        "unit": "kg",
        "costPrice": 75,
        "sellPrice": 88,
        "mrp": 90,
        "quantity": 0,
        "reorderLevel": 25,
        "hsnCode": "1006",
        "gstRate": 5,
    },
    {
        "id": "LOOSE-DAL",
        "name": "Loose Toor Dal",
        "brand": None,
        "isLoose": True,
        "unit": "kg",
        "costPrice": 120,
        "sellPrice": 135,
        "mrp": 140,
        "quantity": 0,
        "reorderLevel": 15,
        "hsnCode": "0713",
        "gstRate": 5,
    },
]


def run():
    print("Seeding database...")
    for prod in SEED_PRODUCTS:
        try:
            insert_row("Product", prod)
            print(f"  ✓ {prod['name']}")
        except Exception as e:
            if "duplicate" in str(e).lower() or "unique" in str(e).lower():
                print(f"  ↻ {prod['name']} exists, skipping")
            else:
                print(f"  ✗ {prod['name']}: {e}")
    print("Done.")


if __name__ == "__main__":
    run()