import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from services.db import get_bill_with_items
from config import SUPABASE_URL
from langchain_core.tools import tool


def generate_invoice_pdf(bill_id: str) -> str:
    """Generate a GST-compliant invoice PDF for a finalized bill."""
    bill, items = get_bill_with_items(bill_id)
    if not bill:
        return f"Error: Bill {bill_id} not found."
    if bill["status"] != "FINALIZED":
        return f"Error: Bill {bill_id} is not finalized."
    
    pdf_path = f"invoice_{bill_id[:8]}.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4
    
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(20*mm, height - 20*mm, "TAX INVOICE")
    
    c.setFont("Helvetica", 9)
    c.drawString(20*mm, height - 28*mm, f"Bill ID: {bill_id}")
    c.drawString(20*mm, height - 34*mm, f"Date: {bill['createdAt'][:19]}")
    c.drawString(20*mm, height - 40*mm, f"Payment: {bill['paymentMethod'] or 'N/A'}")
    
    # Table header
    y = height - 50*mm
    c.setFont("Helvetica-Bold", 8)
    col_x = [20*mm, 80*mm, 130*mm, 150*mm, 170*mm, 190*mm]
    headers = ["Item", "HSN", "Qty", "Rate", "GST%", "Total"]
    for i, h in enumerate(headers):
        c.drawString(col_x[i], y, h)
    
    y -= 5*mm
    c.setFont("Helvetica", 8)
    c.line(20*mm, y + 2*mm, 190*mm, y + 2*mm)
    
    for item in items:
        if y < 30*mm:
            c.showPage()
            y = height - 20*mm
        
        prod = item["Product"]
        name = prod["name"][:25] if prod else item["productId"]
        hsn = prod["hsnCode"] if prod and prod["hsnCode"] else "-"
        qty = str(item["quantity"])
        rate = f"₹{item['unitPrice']:.2f}"
        gst = f"{item['gstRate']}%"
        total = f"₹{item['total']:.2f}"
        
        c.drawString(col_x[0], y, name)
        c.drawString(col_x[1], y, hsn)
        c.drawString(col_x[2], y, qty)
        c.drawString(col_x[3], y, rate)
        c.drawString(col_x[4], y, gst)
        c.drawString(col_x[5], y, total)
        y -= 5*mm
    
    # Tax summary
    y -= 5*mm
    c.line(20*mm, y, 190*mm, y)
    y -= 6*mm
    
    c.setFont("Helvetica-Bold", 9)
    c.drawString(130*mm, y, "Taxable Value:")
    c.drawString(170*mm, y, f"₹{sum(float(i['taxableValue']) for i in items):.2f}")
    y -= 5*mm
    c.drawString(130*mm, y, "CGST:")
    c.drawString(170*mm, y, f"₹{sum(float(i['cgstAmount']) for i in items):.2f}")
    y -= 5*mm
    c.drawString(130*mm, y, "SGST:")
    c.drawString(170*mm, y, f"₹{sum(float(i['sgstAmount']) for i in items):.2f}")
    y -= 5*mm
    c.setFont("Helvetica-Bold", 11)
    c.drawString(130*mm, y, "Grand Total:")
    c.drawString(170*mm, y, f"₹{float(bill['totalAmount']):.2f}")
    
    # Footer
    y -= 15*mm
    c.setFont("Helvetica", 7)
    c.drawString(20*mm, y, "Generated by Kirana Agent | Prices inclusive of GST where applicable")
    
    c.save()
    return pdf_path


@tool
def create_invoice_pdf(bill_id: str) -> str:
    """Tool wrapper: Generate GST invoice PDF for a bill."""
    return generate_invoice_pdf(bill_id)